# .:: Pushover ::.

# - platform: pushover
#   name: pushover
#   api_key: !secret pushover_api_key
#   user_key: !secret pushover_user_key

# .:: Telegram ::.

- platform: telegram
  name: telegram
  chat_id: !secret telegram_chat_id

# .:: HTML5 ::.
# - platform: html5
#   name: HTML5
#   gcm_api_key: !secret chrome_api_key
#   gcm_send_id: !secret chrome_sender_id