# .:: Set AppleTV Volume when switched ::.
- alias: 'Set AppleTV Volume'
  trigger:
    - platform: template
      value_template: "{% if is_state_attr('media_player.living_room', 'source', 'AppleTV') %}true{% endif %}"
  # condition:
    # - condition: template
    #   value_template: "{%- if is_state_attr('media_player.living_room', 'volume_level', '.6375') %}true{% endif -%}"
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room
      data:
        volume_level: "0.6"

