- alias: Restart HA
  trigger:
    platform: state
    entity_id: input_boolean.restart_ha
    from: "off"
    to: "on"
  action:
    - service: notify.telegram
      data:
        title: ''
        message: 'Home Assistant is now restarting.'
    - service: homeassistant.restart