- alias: Test kitchen lights
  trigger:
    - platform: state
      entity_id: input_boolean.random_lights
      from: "off"
      to: "on"

  action:
    - service: light.turn_on
      # entity_id: media_player.living_room
      data:
        brightness: 120
        transition: 3
        entity_id: group.kitchen_lights
