# .:: Make sure that the Onkyo always stays on ::.
- alias: 'Keep the media player on'
  trigger:
    - platform: state
      entity_id: media_player.living_room
      state: "off"
  # condition:
    # - condition: template
    #   value_template: "{{ not is_state('input_boolean.restart_notification', states('binary_sensor.override_restart_notification')) }}"
  action:
    - service: media_player.turn_on
      entity_id: media_player.living_room
    - service: media_player.select_source
      entity_id: media_player.living_room
      data:
        source: 'AppleTV'

