- alias: 'Dusk'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: 'dusk_trigger'

- alias: 'Dawn'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: input_boolean.turn_off
    data:
      entity_id: 'dusk_trigger'